// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzjNBc8noqiyn3X3gGEfRowujZcpVTbA',
    appId: '1:6671009037:web:6208cf6839fc18556ddc44',
    messagingSenderId: '6671009037',
    projectId: 'roswalt-my-home',
    authDomain: 'roswalt-my-home.firebaseapp.com',
    storageBucket: 'roswalt-my-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOlYOuAdVkw9Zt0A49oFobHZ_CvgYIas',
    appId: '1:6671009037:android:4e25ccf60c7ea3c46ddc44',
    messagingSenderId: '6671009037',
    projectId: 'roswalt-my-home',
    storageBucket: 'roswalt-my-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALgsCVV7uSM-HuNTw5pWIyC8yfu7MyIT4',
    appId: '1:6671009037:ios:9e88d654b45ae9396ddc44',
    messagingSenderId: '6671009037',
    projectId: 'roswalt-my-home',
    storageBucket: 'roswalt-my-home.firebasestorage.app',
    iosBundleId: 'com.example.roswaltMyHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALgsCVV7uSM-HuNTw5pWIyC8yfu7MyIT4',
    appId: '1:6671009037:ios:9e88d654b45ae9396ddc44',
    messagingSenderId: '6671009037',
    projectId: 'roswalt-my-home',
    storageBucket: 'roswalt-my-home.firebasestorage.app',
    iosBundleId: 'com.example.roswaltMyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzjNBc8noqiyn3X3gGEfRowujZcpVTbA',
    appId: '1:6671009037:web:b016908a4426b8f76ddc44',
    messagingSenderId: '6671009037',
    projectId: 'roswalt-my-home',
    authDomain: 'roswalt-my-home.firebaseapp.com',
    storageBucket: 'roswalt-my-home.firebasestorage.app',
  );
}
